### ISSUE TITLE
Binder not called when Battery Optimization is on

### ISSUE THREAD

**Issue by sairajsawant** [GoogleChromeLabs/android-web-payment#10]
Chrome is unable to communicate with the binder to call `isReadyToPay` when battery optimization is turned on. However, Google Pay is invoked for the same battery setting. Any ideas about how can this be fixed ? Thanks.

**Comment by agektmr** [comment]
@sahel-sh @rsolomakhin any idea on this issue? Can you have a look into it?

**Comment by rsolomakhin** [comment]
This sounds like it could be a Chrome bug, so I've filed https://crbug.com/1144153 to keep track of this issue. Let's continue the conversation there.
